ALTER TABLE `player_vehicles`
ADD COLUMN IF NOT EXISTS `nosColour` TEXT NULL DEFAULT NULL;
ALTER TABLE `player_vehicles`
ADD COLUMN IF NOT EXISTS `traveldistance` INT(50) NULL DEFAULT 0;
ALTER TABLE `player_vehicles`
ADD COLUMN IF NOT EXISTS `noslevel` INT(10) NULL DEFAULT 0;
ALTER TABLE `player_vehicles`
ADD COLUMN IF NOT EXISTS `hasnitro` TINYINT(0) NULL DEFAULT 0;